name = "JPkg"
uuid = "0775afdd-9af1-4f0a-84c7-da6ca2acbae0"
authors = ["Matthew"]
version = "0.1.0"

[compat]
julia = "1.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
